### PR TITLE
Added PnP PS 2.4.0 release announcement

### PR DESCRIPTION
**Pull request by gautamdsheth**
## Category

- [ ] Content fix
- [x] New article

## Related issues

NA

## Contents of the Pull Request

Added new release announcement for PnP PowerShell 2.4.0 release

### CODE REVIEW

**Comment by LuiseFreese** [comment]
@gautamdsheth shall i merge this or will publish the announcement yourself?

**Comment by gautamdsheth** [comment]
@LuiseFreese - can you please merge it ?

**Comment by LuiseFreese** [comment]
merged. Site is building as we speak! Congrats on the new release! 🧡

**Comment by gautamdsheth** [comment]
Thank you 😊🙌

**Pull request merged**
