### PR TITLE
Added back to pnp home site button

### LINKED ISSUE #155: Implement BACK button from blog to main site
Right now there is no way to get from https://pnp.github.io/blog to https://pnp.github.io, our main landing page.

### PR DESCRIPTION
**Pull request by Adam-it**
## Category

- [X] Content fix

## Related issues

- fixes #155

### 🎯Aim

The aim of this PR is to add some kind of link at the blue top header of the site that will redirect user to the PnP community home site.

### ✅ What was done

- [X] I added new site variables with link url and name for the new header button
- [X] added new simple partial and used it in the header
- [X] removed hamburger button from header

### 📸 Result

image

🎥 How it works 👇

https://user-images.githubusercontent.com/58668583/182043733-7cb5bc77-7a29-4edd-b24a-a31a3003cdb5.mp4

removed the navigation toggle button from header which had no functionality was black
image

### 💬 Additional comment
Also 😜... for now the link name is "PnP Community Home Page" as I could not think of anything better but please fell free to suggest a better one

### CODE REVIEW

**Comment by LuiseFreese** [comment]
Thank you @Adam-it for contributing! The new BACK link is awesome, I will happily merge this 😍. 
I fully agree on the hamburger icon - Think it's best to remove this. If you want to tackle this, I am looking forward that you add this to this PR.

**Comment by Adam-it** [comment]
> Thank you @Adam-it for contributing! The new BACK link is awesome, I will happily merge this 😍. 
> I fully agree on the hamburger icon - Think it's best to remove this. If you want to tackle this, I am looking forward that you add this to this PR.

Sure.
Will add this commit today 👍
Have a awesome day 🤩

**Comment by Adam-it** [comment]
@LuiseFreese 
done ✅
I updated the PR description as well. 
let me know if there is something else 👍

**Comment by LuiseFreese** [comment]
squashed and merged! excited now for the site to build! Thank you again! This is a super cool improvement!

**Pull request merged**
