### PR TITLE
Contibution power platfom

### PR DESCRIPTION
**Pull request by DuvanBaena**
## deploy static web sites with powerplatform / third contribution

- [x] twitter (*djb349*)

> My name is Duvan. Nice to meet you. I am from Colombia, and I would like to share with you some things I enjoy: I enjoy reading and learning about many topics , but technology is always in my mind. I define myself as a quiet and happy person, with the ability to listen and then look for a solution..
>

### CODE REVIEW

**Comment by LuiseFreese** [comment]
hi @DuvanBaena - thank you for your contribution - can you please translate line 25 and update the index.md? Thank you.

**Comment by DuvanBaena** [comment]
> hi @DuvanBaena - thank you for your contribution - can you please translate line 25 and update the index.md? Thank you.

**Comment by DuvanBaena** [comment]
> > hi @DuvanBaena - thank you for your contribution - can you please translate line 25 and update the index.md? Thank you.

**Comment by DuvanBaena** [comment]
sure, Thanks you!

**Comment by LuiseFreese** [comment]
there is still non-english content...

**Comment by DuvanBaena** [comment]
> there is still non-english content...

The fix was successful, check please!!!

**Pull request merged**
