### PR TITLE
New article: PnP PowerShell 1.10 released

### PR DESCRIPTION
**Pull request by gautamdsheth**
#### Category

- [ ] Content fix
- [x] New article

#### Contents of the Pull Request

Add a new article detailing the PnP PowerShell 1.10 changes.

Please let me know if you need to change/add/update anything.

### CODE REVIEW

**Comment by LuiseFreese** [comment]
thanks for the article @gautamdsheth  and @KoenZomers 👏 - as you didn't define a correct path to a tn image in the frontmatter, I took care of that. If you want to change the current image to something else, please feel free to do that :-)

Your PR is already merged into main and the site is deployed again.

**Comment by gautamdsheth** [comment]
@LuiseFreese - thanks for fixing it , my bad :( 

However , I am looking at the blog: https://pnp.github.io/blog/pnp-powershell/pnp-powershell-v1-10/ 

It doesn't have that image, anything I need to do, maybe I missed something or maybe you can check it ?

**Comment by LuiseFreese** [comment]
Hey @gautamdsheth - it is the thumbnail image for the blog post, which means that it appears in the overview site of all blog posts with that image. 

you can check this here: https://pnp.github.io/blog/ (you will need to scroll down a bit)

For your convenience, here is a screenshot:
image

If you want to insert the image IN your blog post, please do with 

`alt text`

Let me know if I can help with anything.

**Comment by gautamdsheth** [comment]
Got it , thanks !

**Pull request merged**
