### PR TITLE
New article save data to app folder on user OneDrive

### PR DESCRIPTION
**Pull request by Adam-it**
#### Category

- [ ] Content fix
- [X] New article

#### Contents of the Pull Request

🎯 Aim
The aim of this PR is to add a new blog post describing how we may save to application personal folder on OneDrive using MS Graph in Spfx solutions.

🙋‍♂️ Help needed
As this is the first time I added the blog post this way (as PR to repo, before I did it with adding new Article from the web page) I would really appreciete any feed if I added the images tag properly 👍. Also any other tips along the way would be really nice 😉

### CODE REVIEW

**Comment by LuiseFreese** [comment]
hey @Adam-it - I will look into this today! Thank you for contributing, I will keep you updated!

**Comment by LuiseFreese** [comment]
Great work @Adam-it  - I saw in the frontmatter your `//TODO add image` - will you provide an image as a thumbnail? If you don't have an image, you can go to the assets folder - I put some images there that can be used, but if you pick one image of your images folder, that would be better. 

YOU ROCK 😎

**Comment by Adam-it** [comment]
@LuiseFreese thanks for noticing this. I totally forgot about that image. I will add something really soon 👍.

**Comment by Adam-it** [comment]
@LuiseFreese I added the thumbnail image and updated the index.md. BTW thanks for the additional commit in correcting the article contents 👍. I hope you liked it 😉.
[keep on rokin](https://youtu.be/DvxxdZpMFHg?t=44)

**Comment by LuiseFreese** [comment]
@Adam-it  thank you for this great article,  yes I liked it very much!

**Pull request merged**
