### PR TITLE
A Timesheet Canvas and Model Driven Power App

### PR DESCRIPTION
**Pull request by Dlutchy**
## Category

- [ ] Content fix
- [x] New article

## Contents of the Pull Request
A Power App demo that is used for Time Sheeting purposes. The app consist of:
- Canvas App for the user to enter times.
- Model Driven App where Projects are created and timesheets can be exported to Excel for reporting.
- Data is Stored in Dataverse therefore a Power App Premium license is required. 

YouTube video of how to use this App can be found at https://www.youtube.com/watch?v=zgKe9Pu7nWA

Authored by: Darren Lutchner (May 2022)
Twitter: https://twitter.com/assist_365

### CODE REVIEW

**Comment by LuiseFreese** [comment]
Hi @Dlutchy - thanks for your first PR in this repo! I saw that you committed two files- the index.md only containing the metadata of the article and a thumbnail image. 
Do you need any support to turn this into a blog post (in which of course we can embed a video)? Most community blog posts start with an intro to the problem that is being solved, then give an overview on tools/services that come into play and then explain how the different parts integrate with each other. 

Let me know how I can help. 

Luise

**Comment by Dlutchy** [comment]
Hi @LuiseFreese thanks. Is it that I I just need to change the wording to make it into a blog post or did I do something in Git incorrectly?
What are my next steps.
Thanks Darren

**Comment by LuiseFreese** [comment]
As far as I can see, in GitHub it looks almost correct - I will move your files to CONTENT/BLOG/TIMESHEET-APP from CONTENT/TIMESHEET-APP. 

You will write your article in the INDEX.MD file that you created below the metadata (front matter) of that file.

**Comment by Dlutchy** [comment]
Will do thank you. Do I need to change the location for next time?

**Comment by LuiseFreese** [comment]
ideally, use the correct folder content/post and then create your folder inside of it. But there is no harm done when I move the files. 

we are all learning :-)

**Comment by Dlutchy** [comment]
Hi @LuiseFreese do I need to do anything here to fix this?

**Comment by LuiseFreese** [comment]
Yes, you would need to write an actual blog post. You post only contains a link to your youtube video :-)

**Comment by Dlutchy** [comment]
I added Blog content. Still not exactly sure of the requirements and if it works. Let me know if I need to do anything else.

**Comment by LuiseFreese** [comment]
I merged your commits, will now edit the article (mostly formatting issues) and then publish it. Thank you for contributing.

**Pull request merged**
