### PR TITLE
How to add pre-configured SPFx Teams Tab to a channel

### PR DESCRIPTION
**Pull request by mgwojciech**
## Category

- [ ] Content fix
- [ x] New article

## Contents of the Pull Request

In this article I go through steps required to automate adding a pre-configured SPFx web part as a Teams Tab to any channel.
Pre configuration includes setting up the associated SharePoint site with a web part configuration ready to be consumed by MS Teams.

### CODE REVIEW

**Comment by LuiseFreese** [comment]
hey @mgwojciech thank you fort your PR - I made some changes to the file (mostly formatting issues) and added a (generic) thumbnail image. If you'd like to have another thumbnail image, please upload it into the `/how-to-add-preconfigured-spfx-teams-tab/images` folder and exchange the image link in the `index.md` file on line 10. 
For future posts: 

- headings (##, ###, #### etc) need to be surrounded by an empty line
- code blocks start with ``` (without a space before) and also need an empty line around them
- if you make an unordered list, don't indent before the `-`

(it's complaining on a very high level here!! - you did great! )

**Comment by mgwojciech** [comment]
@LuiseFreese - thanks for the feedback :) I'll be better next time :)

**Comment by mgwojciech** [comment]
What linter are You using? Maybe I can use the same?

**Comment by LuiseFreese** [comment]
I use this one

https://github.com/yzhang-gh/vscode-markdown

which comes with some amazing features if you often need to write markdown

**Pull request merged**
