### PR TITLE
Content cleanup/scrub attachments from community calls

### PR DESCRIPTION
**Pull request by andrewconnell**
## Category

- [x] Content fix
- [ ] New article

## Related issues

- n/a

## Contents of the Pull Request

Per discussion wit @VesaJuvonen, it was decided to remove all presentation attachment downloads (PPTX & PDF) from site codebase. All calls are recorded & published to YouTube, so attendees can get the content from watching the video.

🚨 In the future, DO NOT commit call presentations (PPTX & PDF) or accept PR's with large files in them without justification.

### WHY remove them?

The presentations from the calls accounted for over 1GB, making cloning the repo a poor experience for new contributors & making site deployments slower than necessary. Cloning the entire history of the repo will still pull them down, but a shallow clone of depth=1 will make the clone MUCH faster once this is merged in.

### CODE REVIEW

**Comment by VesaJuvonen** [comment]
Clean up, clean up, clean up 👏👏👏

**Comment by andrewconnell** [comment]
Thanks... hey @ViewPorter, making sure you're aware of this for future wrapup posts for community calls.

Please refer to my original comment above, specifically the **WHY**, for a new direction on how we're not going to include the slide decks either as PPTX or PDF in future community call wrapups.

**Comment by ViewPorter** [comment]
Hello andrewconnell.  ViewPoter understands this directive.  If you are removing decks from existing posts, you may need to remove the {{< attachments >}} tag at end of each post.  I will continue to create and associate to post an images folder containing thumb and together mode images.  These can exist without the {{< attachments >}} tag.  Cheers,  Andrew

**Comment by andrewconnell** [comment]
> If you are removing decks from existing posts, you may need to remove the {{< attachments >}} tag at end of each post.

Please review the commits in this PR as that address this point.

**Comment by ViewPorter** [comment]
You're a step ahead as expected.  Thanks.

**Pull request merged**
