### PR TITLE
Update the display of the images and also fixed the images names

### PR DESCRIPTION
**Pull request by arunkumarperumal**
#### Category

- [x] Content fix
- [ ] New article
- [ ] Example checked item (*delete this line*)

#### Contents of the Pull Request

> Used a different way of showing the images
> Fixed the images names and also made sure it is same name as it seems to be case sensitive.

### CODE REVIEW

**Comment by LuiseFreese** [comment]
Hey Arun,

I replaced the image shortcode by md syntax - and pics are showing on the website :-)

**Comment by arunkumarperumal** [comment]
Thanks Luise, 

I still see three issues in the md syntax. more with the file names and extensions. my bad :(

FAQ Web Part

Default Screen 

Type Options

Can you please update...

**Comment by LuiseFreese** [comment]
you can PR this :-)  let me know if you need help. I will merge asap :-)

**Comment by arunkumarperumal** [comment]
I have already fixed, but have a merge conflict. Need help with fixing the merge conflict

**Comment by LuiseFreese** [comment]
no conflicts showing up here though. Maybe just a hiccup? Site is building right now

**Comment by arunkumarperumal** [comment]
i was able to resolve the conflicts. thanks for merging

**Comment by LuiseFreese** [comment]
we made it 👏👏👏

**Comment by arunkumarperumal** [comment]
Thanks for all the help! 👍👏

**Pull request merged**
