### PR TITLE
SPFx as spyware - updates

### PR DESCRIPTION
**Pull request by kkazala**
## Category

- [x] Content fix
- [x] New article

## Contents of the Pull Request
**Important** This PR has a dependency on 
- https://github.com/pnp/sp-dev-fx-webparts/pull/5203
- https://github.com/pnp/script-samples/pull/724
Please do not approve before the above PR are merged

2nd article in SPFx as spyware series, covering 
- PS script to review spfx extensions and requested permissions, and API permissions granted to the SP service principal
- adding Application Insights tracking to all SPO modern sites, analyzing results and alerts

Reference added to the 1st article from the series

And... tags added to the old Power Platform extensibility articles. I already forgot about this change and as a result, everything in one PR. I'm sorry, can we leave it like that?
Spaces added automatically by "Prettier", hope it's ok?

### CODE REVIEW

**Comment by VesaJuvonen** [comment]
These are great articles to educate the ecosystem - however - we seem to be missing the technical detail that to be able to install or start using SPFx solutions - they have to be deployed and installed by administrators. 

Would absolutely include that detail already to the part 1 to avoid confusion - as now it gives an impression that anyone can start using SPFx solutions - which of course it not the case... this was the key differentiator vs the script editor web part we had in the classic experience - where admin and governance for the extensibility was not required... with the SPFx - any solution which is installed on the tenant has to be explicitly approved by the tenant administrator - or the app administrator if responsibility is delegated forward - so there's additional governance and admin controls by design for the IT - which also can control the usage of the SPFx solutions from one central location. This quite important detail seems to be missing at least from the part 1 on this series.

As said - otherwise it's great that we educate the customers on the different considerations, but would love to get above details noted to avoid confusion.

**Comment by kkazala** [comment]
Thx @VesaJuvonen  for the feedback. I will update the articles to elaborate more on roles and responsibilities. 
With the site-level app catalog, however, once enabled, site owners can install the solutions themselves. The attack surface is smaller, but not negligible. That's why I mentioned that _"Security Awareness: If site level catalogs are enabled in the tenant, educate the site owners about the risks associated with installing and using third-party solutions._"

I see your point, it's at the very end and could be easily missed. 
Will make an update soon :)

thx again

**Comment by kkazala** [comment]
@VesaJuvonen Please have a look. I think that these two articles in the series now paint a more complete picture :)

**Comment by VesaJuvonen** [comment]
*"With the site-level app catalog, however, once enabled, site owners can install the solutions themselves. "*

However - you need to be a tenant administrator to create site-level app catalog, providing IT full governance and control on allowing site owners to do this. There's no way end users can start using SPFx solutions without control and governance from the administrators.

In general site-level app catalogs only have really minimal use currently worldwide for these exact reasons - as it would allow the site collection owners to accidently cause issues - after the usage has been allowed by the administrators.

**Comment by kkazala** [comment]
"However - you need to be a tenant administrator to create site-level app catalog,"- SharePoint Admin is enough
"In general site-level app catalogs only have really minimal use currently worldwide" - we currently have 10 sites with site-level app catalog. 

Not sure what you'd like me to correct here. How about I quote you? This would be fantastic, to have your statement here.

It is not my goal to claim that SPO securing is bad. It isn't. But after hearing things like:
- "we only allow delegated permissions" - meaning we have it covered and nothing to worry about
- "we are now trying to find out which spfx solution has which permissions"- rrrrightt
- "ok, so I'm just going to search for these 2 lines of code [retrieving access token]"- ehmm.... yeah

I decided we really have to discuss this topic. It's not about vulnerabilities in SPFx, SPO or M365. We are the vulnerability

**Comment by kkazala** [comment]
Removed all the other changes from the PR to isolate the topic

**Comment by VesaJuvonen** [comment]
Thx @kkazala on the updates. This is incredibly important topic which has to be for sure discussed so that our customers and partners understand what they are consenting and what the solutions can do within their environment. Transparency is for sure the key and liked following callout a lot - "This **approval process is far more than just a formality** and must be taken extremely seriously. The decision to approve a solution can have significant implications for the security of the entire tenant."

Edits are definitely great and provide more insights on the process - as initially the admin role was not discussed in the article - and it simply called out that solutions can access information - which is not wrong - but it can only happen if administrators approve the solutions. That's really the key on the modern SharePoint experiences - with SPFx vs the classic SharePoint with script editor web part - which technically allowed these kind of things to be done WITHOUT admin control - as any site owner could copy script and place that on the site.

Since classic SharePoint is still supported (yes - amazing it still is) - we have introduced the default settings with the noscript setting - which by default blocks end users to use script editor web part in classic SharePoint. So - there's at least recommendations for this from Microsoft - even though some customers are still using classic and they allow script editor web part usage - which is a clear risk.

On the PR - definitely ok to get merged - however it is now referencing the part 2 article - which was removed from this PR, so would not merge this yet... So - would suggest to get the part 2 back - or edit this to remove that link for now - and then submit a new PR when you are ready with that.

Thank you for helping to increase the awareness of the security topics - critical for the ecosystem to understand 🙏

**Comment by kkazala** [comment]
@VesaJuvonen  Fantastic, I'm happy you like the updates :)
I re-added the Part II now, and also (in Part II) included additional suggestion for automated cleanup of unused API permissions.
I'm referencing scripts from my gist now, because I just did a https://github.com/pnp/script-samples/pull/732 to add them to the official samples, but i know it takes few days and I would like to push the update to the part I as as soon as possible.

Do you know how long it takes to approve webpart samples? 
I'm suggesting tenant-wide deployment of Application Customizer solution for tracking external API calls and I am now linking the sample from my GitHub account, because the https://github.com/pnp/sp-dev-fx-webparts/pull/5203 is still pending 

thank you for all your help and support =)

**Comment by VesaJuvonen** [comment]
Just to follow up on here - you are not forgotten @kkazala.

Your PR in the SPFx web parts should be processed this weekend and then we can merge these updates in early next week. Thanks for your patience.

**Comment by kkazala** [comment]
@VesaJuvonen I updated the links to the scripts and the webpart, so let's merge, if it's OK with you?
Otherwise I will keep updating it and will never finish :D

**Comment by kkazala** [comment]
@VesaJuvonen do you think we could merge it some time soon? :)

**Comment by Adam-it** [comment]
> @VesaJuvonen do you think we could merge it some time soon? :)

ooops I think this was missed for some time now 😮
@kkazala sorry for that. I will try to ping @VesaJuvonen on this and merge it ASAP.

**Comment by VesaJuvonen** [comment]
@kkazala I'm so so so sorry for missing this completely as it dropped from my radar - I get way too many GitHub comments in notification/email format, which makes it impossible to follow up on them, but it's a bad excuse. I should have ensured that we get our discussion finalized and published. Thanks @Adam-it for the direct message on getting this processed 🙏

I've now updated the date for the part 2 article - for today - so that it will not be buried on the history.

**Comment by Adam-it** [comment]
@VesaJuvonen thanks a lot for your help 👍
This will also get a mention on the upcoming Viva Community Call
@kkazala did you already opt-in our recognition program? 
https://pnp.github.io/recognitionprogram/
You should definitely do that haven't already and get the Blog Author badge

**Pull request merged**
