### PR TITLE
Added display-file-viewing-card-with-List-Formatting

### PR DESCRIPTION
**Pull request by tecchan1107**
## Category

- [ ] Content fix
- [x] New article

## Contents of the Pull Request

I wrote an article related to List Formatting.

### CODE REVIEW

**Comment by tecchan1107** [comment]
I closed it because I want to rewrite it.
I will pull request again later.

**Comment by appieschot** [comment]
Anything we can do to make the writing experience better?

**Comment by tecchan1107** [comment]
Hi @appieschot ! Thank you so much!!
I am not very good at English. And this is my first article in English. So I am very worried that I am using wrong English😖😖
If possible, I would like you to check if my English is correct.
https://github.com/pnp/blog/pull/245

**Comment by appieschot** [comment]
@tecchan1107  you are doing great! @LuiseFreese has already processed the PR but I had no comments on the English! Don't worry to much about the text not being perfect! Done is better than perfect 🦾

**Comment by LuiseFreese** [comment]
@tecchan1107 most contributors are not english native speakers. you are doing great and I appreciate your content a lot! We are all learning! Keep up the good work! As @appieschot  mentioned: looks good!

**Pull request closed without merging**
