### PR TITLE
Added How to change the background color of cards in the Board View

### PR DESCRIPTION
**Pull request by tecchan1107**
## Category

- [ ] Content fix
- [x] New article

## Contents of the Pull Request

I wrote an article on how to change the background color of cards in board view.

### CODE REVIEW

**Comment by tecchan1107** [comment]
I have found that after applying the formatting once, clicking [Customize Card] appears to clear the formatting. In reality, the formatting is not cleared until the [Save] button is clicked, but this may be confusing.

sample

So I would like to change the process from [Format current view] instead of [Customize Card]. After formatting once, when I click [Format current view], I get a screen of code and the formatting is not cleared.

I will draft this pull request once. I will comment as soon as the fix is complete.

I am sorry for any inconvenience this may cause you🙇‍♂

**Comment by tecchan1107** [comment]
I fixed it.

**Comment by LuiseFreese** [comment]
Thank you for contributing, you are awesome!

**Comment by tecchan1107** [comment]
Thank you @LuiseFreese 🙏✨!!

**Pull request merged**
