### PR TITLE
Added community post for Patterns and Practices for SPFx Development

### PR DESCRIPTION
**Pull request by Dipesh-Bhanani**
## Category

- [ ] Content fix
- [x] New article

## Contents of the Pull Request

The community post contains guidance on patterns and practices for SharePoint Framework development. I have added best practices based on Microsoft guidance and my experience on the platform. My Twitter handle is @AskDipesh.

### CODE REVIEW

**Comment by LuiseFreese** [comment]
hey @Dipesh-Bhanani  -thank you for your contribution. Can you provide a thumbnail image? Ot should sit in an `images` subfolder in your blogs posts' folder and you will refer to it in the metadata/front matter of your index.md file. 

Let me know if you have questions.

**Comment by Dipesh-Bhanani** [comment]
> hey @Dipesh-Bhanani -thank you for your contribution. Can you provide a thumbnail image? Ot should sit in an `images` subfolder in your blogs posts' folder and you will refer to it in the metadata/front matter of your index.md file.
> 
> Let me know if you have questions.

@LuiseFreese There isn't any image used in this community post which is why I haven't added the thumbnail. Is there any specific image that you would like me to add?

**Comment by LuiseFreese** [comment]
Hi there again @Dipesh-Bhanani this is how our website at aka.ms/m365pnp/blog looks like: 

image

It's a good practice to include a thumbnail image, this is more engaging for most people. You can find beautiful stock images for example at unsplash.com

**Comment by LuiseFreese** [comment]
@Dipesh-Bhanani a screenshot of the blog is not really engaging. Would you mind if I pick a picture for you?

**Comment by Dipesh-Bhanani** [comment]
> Hi there again @Dipesh-Bhanani this is how our website at aka.ms/m365pnp/blog looks like:
> 
> It's a good practice to include a thumbnail image, this is more engaging for most people. You can find beautiful stock images for example at unsplash.com

@LuiseFreese Thanks for tips. I have created an image from the blog content itself. Let me know if that's good otherwise I will get something good from unspalsh.com

**Comment by Dipesh-Bhanani** [comment]
> @Dipesh-Bhanani a screenshot of the blog is not really engaging. Would you mind if I pick a picture for you?

@LuiseFreese Updated the thumbnail image. Hope this looks good. If not, feel free to pick a relevant picture. Thanks again.

**Comment by Dipesh-Bhanani** [comment]
> @Dipesh-Bhanani a screenshot of the blog is not really engaging. Would you mind if I pick a picture for you?

@LuiseFreese I had updated the thumbnail image. Let me know if there is any further action item required to publish the post. Thanks.

**Pull request merged**
