### PR TITLE
New blog post cli how cool is that permission commands

### PR DESCRIPTION
**Pull request by Adam-it**
## Category

- [ ] Content fix
- [X] New article

## Contents of the Pull Request

The aim of this PR is to add a new blog post promoting permission commands added not so long ago to CLI for Microsoft 365 and thank the contributors for all of their amazing work 🤩

### CODE REVIEW

**Comment by Adam-it** [comment]
opening this a s draft as I am waiting for one last permission command to be merged to CLI for Microsoft 365

**Comment by Adam-it** [comment]
> opening this a s draft as I am waiting for one last permission command to be merged to CLI for Microsoft 365

ok all pushed 💪

**Comment by Adam-it** [comment]
@LuiseFreese sorry for bothering 🙏. Do you maybe need anything more from my side before reviewing this one?

**Comment by LuiseFreese** [comment]
SO SORRY! I somehow thought this is a CLI new version announcement- which you CLI people handle on your own! 

Will get this processed asap!

**Comment by Adam-it** [comment]
> SO SORRY! I somehow thought this is a CLI new version announcement- which you CLI people handle on your own!
> 
> Will get this processed asap!

That's totally fine and don't worry. I just thought I forgot about something 😋. Anyway there is no rush 👍
You are doing and awesome job 😍. You rock 🤩

**Pull request merged**
