### PR TITLE
PnP PowerShell 2.1.1 release

### PR DESCRIPTION
**Pull request by gautamdsheth**
## Category

- [ ] Content fix
- [x] New article

## Related issues

NA

## Contents of the Pull Request

Added a new article about the release of PnP.PowerShell 2.1.1

### CODE REVIEW

**Comment by gautamdsheth** [comment]
@LuiseFreese / @VesaJuvonen  - can you please approve and merge this PR ?

**Comment by LuiseFreese** [comment]
Just checking - you want this to be published tomorrow?

**Comment by gautamdsheth** [comment]
Today :)

**Comment by gautamdsheth** [comment]
Thanks @LuiseFreese , much appreciated 🙏!!

**Comment by LuiseFreese** [comment]
All good, modified the date so that it got published right now. Have a lovely day :-)

**Pull request merged**
