### PR TITLE
New blog post with some tips and tricks about CLI for M365

### PR DESCRIPTION
**Pull request by Adam-it**
## Category

- [ ] Content fix
- [X] New article

## Contents of the Pull Request

the aim of this PR is to add a new blog post that will describe some tips and tricks about CLI for Microsoft 365

### CODE REVIEW

**Comment by Adam-it** [comment]
Got some comments from @waldekmastykarz I want to introduce 👍

**Comment by Adam-it** [comment]
@LuiseFreese ready to review 👍👍

**Comment by LuiseFreese** [comment]
hey @Adam-it  - will go though this asap and let you know. Thank you, you rock (as always!)

**Comment by Adam-it** [comment]
@LuiseFreese I noticed the check "link checker" keeps on failing on some other articles
image

would you like me to add an issue for that, assign it to myself and try to fix it?

**Comment by LuiseFreese** [comment]
help is always welcome, @Adam-it 

if the link is really dead, I usually try to find the correct URL or - if that is not possible - I remove the link from the article. Of the link just gave a timeout when the linkchecker ran but does work, we leave it as-is.

**Comment by Adam-it** [comment]
@LuiseFreese I noticed there is a automatically generates issue for this -> https://github.com/pnp/blog/issues/497
do you want me to assign that one to myself or create a new one ?

**Comment by LuiseFreese** [comment]
@Adam-it you can use issue 497 for that, thank you.

**Pull request merged**
