### PR TITLE
Fix link checker report

### PR DESCRIPTION
**Pull request by Adam-it**
## Category

- [X] Content fix
- [ ] New article

## Related issues

#497

### 🎯 Aim

The aim of this PR is to fix (or at least try to fix) broken link in some of the articles

### 🤔 Remarks

I had no idea what I should do with broken emails 😉 except that I should not send them any emails 🙂. Any suggestion how to address this will be super helpful 👍

### ✅ What was done

Please double check the commits history for more details. I tried to added a clean commit history to see exactly  what was removed and why and what was modified
- [X] removed link to chrome store extension (not present in store anymore)
- [X] updated the link to graph protection info
- [X] updated the link to building publishing connectors
- [X] updated the link to pnp weekly show (wrong index changed from 17 to 170)

### CODE REVIEW

**Comment by Adam-it** [comment]
image

DanceCuteGIF

**Comment by Adam-it** [comment]
@LuiseFreese not sure if what I done is correct 🤔. Please check the commit history. Each change was done as separate commit to make it easy to revert if I have done something wrong 🙂. The link checker seems to be ok now. 
Let me know if there is something more I may do 👍
Have a awesome week 🤩

**Comment by LuiseFreese** [comment]
Great job, @Adam-it ! 

Only one little correction - we never do the language code (such as `en-us` in links. The browser figures out which language to display, if you remove that.

Thank you again! you rock :-)

**Comment by Adam-it** [comment]
> Great job, @Adam-it !
> 
> Only one little correction - we never do the language code (such as `en-us` in links. The browser figures out which language to display, if you remove that.
> 


aaa sure... makes total sense 😉. Thanks for the fix 👍 I will remember it when doing this kind of fix next time 👍. Will be on the look out if the link checker will fail again and try to help out 👀.

> Thank you again! you rock :-)

You too 🤩

**Pull request merged**
