### PR TITLE
React FAQs Community Sample Blog post

### PR DESCRIPTION
**Pull request by arunkumarperumal**
#### Category

- [ ] Content fix
- [x ] New article
- [] Example checked item (*delete this line*)

#### Contents of the Pull Request

> Added a new blog post describing how to mange the React-FAQs community sample.

### CODE REVIEW

**Comment by LuiseFreese** [comment]
Hey @arunkumarperumal - thank you! I will look into this today! Thank you for  contributing - you rock! 💪

**Comment by LuiseFreese** [comment]
Thanks again, that's a great article!

**Comment by arunkumarperumal** [comment]
@LuiseFreese can you please share the blog link or url

**Comment by LuiseFreese** [comment]
Here you go https://pnp.github.io/blog/post/community-sample-faqs-with-propertyfieldcollectiondata/

**Comment by arunkumarperumal** [comment]
@LuiseFreese, Images on the post is not displaying. Is it because of spaces in the name of the images.

**Pull request merged**
