### PR TITLE
Fix issue with not installing the right version of Hugo

### LINKED ISSUE #423: Bug: The docker container installs the wrong version of hugo
When using the docker container included in the repo, and executing `hugo serve`, the `scss` compilation crashes against the [following documented error](https://gohugo.io/troubleshooting/faq/#i-get--this-feature-is-not-available-in-your-current-hugo-version)

This is because the regular version of hugo is installed inside the docker container, while we need the extended version.

It also installs a different version number of hugo (`latest` version) instead of the version used in the release pipeline.

### PR DESCRIPTION
**Pull request by martinlingstuyl**
## Category

- [ ] Content fix
- [ ] New article
- [x] Bug 

## Related issues

- fixes #423

## Contents of the Pull Request

This PR contains an update to the installed version of hugo within the Dockerfile. It will now install the extended version using the same version nr as the release pipeline does.

### CODE REVIEW

**Comment by LuiseFreese** [comment]
hey @appieschot could you kindly have a look at that? We had an issue with a broken build because of Hugo version, I am a bit hesitant here :-)

**Comment by appieschot** [comment]
Hey @martinlingstuyl quick check; we had issues with the `0.101.0` hugo release in our release pipeline (added https://github.com/pnp/blog/commit/0c2239c8d948a83e1e5871ed0ca0273e394d5c89) are you experiencing the same with the docker container? Any specific settings as to the amount of resources available for docker? In the release pipeline the issue was caused by the amount of content that needs to be build from scratch.

**Comment by martinlingstuyl** [comment]
Hi @appieschot, 
Good question. The devcontainer/docker still installs the latest version, so I've now got:

```sh
hugo v0.101.0-466fa43c16709b4483689930a4f9ac8add5c9f66+extended linux/amd64 BuildDate=2022-06-16T07:09:16Z VendorInfo=gohugoio
```

Aside from the scss compilation issues because of the missing extended version, I _did have issues serving_ at first. It ran up against the timeout of 90 seconds and broke off. I don't think I changed anything, but it's now succesfully building in 6-10 seconds time and time again.

I'm not having specific docker resource restrictions in place.

**Comment by appieschot** [comment]
The reason you get a timeout issue of 90 seconds only the first time is because Hugo is smart enough not to build pages already build, so if you run it a few more times the error goes away. In the release pipeline you get a clean environment each time you build, hence the error. 

I would like to argue to keep the docker and release pipeline on the exact same version (fixed to `0.100.2` for now), should be a more consistent experience and we can then move to a newer Hugo version if the issue is solved.

**Comment by martinlingstuyl** [comment]
> The reason you get a timeout issue of 90 seconds only the first time is because Hugo is smart enough not to build pages already build

Apparently you're correct, I've just cloned the git repo afresh (to test), and the build is succeeding with `vmmem` taking up more than 80% CPU and 12GB of memory before doing so 😂. Though not adhering to the timeout. It succeeds in 920995 ms. The second build takes 26000 ms, and after that it evens out at 6-10 seconds.

It's kinda weird though. I see Hugo caches the data in a `tmp/hugo_cache` folder on the linux filesystem. And of course it saves the output in the `public` folder. But if I remove both folders, the build still purrs on in max 10 seconds. There must be some other cache somewhere...

> move to a newer Hugo version if the issue is solved.

Is there an open issue registered with the Hugo product team?

> I would like to argue to keep the docker and release pipeline on the exact same version (fixed to `0.100.2` for now)

I'll update this pull request and relating issue to fix the version number as well.

**Comment by martinlingstuyl** [comment]
I've updated the version number as well to align with the release pipeline.

**Comment by appieschot** [comment]
> > move to a newer Hugo version if the issue is solved.
> 
> Is there an open issue registered with the Hugo product team?


I had a look at the discussion thread here: https://github.com/gohugoio/hugo/issues/4841 when we first encountered that issue. But it seems to be present for a while, and with like 70 comments I just gave up and figured we could stick to the version that was working before 🤷. 

Will squash and merge this commit

**Pull request merged**
